// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "Writers/ConservedWriter.h"

CCZ4::ConservedWriter::ConservedWriter(CCZ4::CCZ4Solver_FV& solver) {
  // @TODO Please insert your code here.
}

CCZ4::ConservedWriter::~ConservedWriter() {
}

void CCZ4::ConservedWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void CCZ4::ConservedWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void CCZ4::ConservedWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 59;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}